apiVersion: apps/v1
kind: Service
metadata:
  name: mvi_analyst_b_db
spec:
  type: ClusterIP
  ports: 
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Endpoints
metadata:
  name: mvi_analyst_b_db
subsets:
  addresses: 
    ip: 10.251.0.6
  ports:
    port: 3306

  containers:
        - name: app
          image: davidsmenesesc/rampup-back
          ports:
            - containerPort: 3000