apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: v1.peladonerd.local
    http:
      paths:
        backend:
          service:
            servicename: mvi-analyst-f-service
            serviceport: 80