apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-movie
  annotations:
    kubernetes.io/ingress.class: ingress-nginx
spec:
  rules:
  - host: mviapp.com
    http:
      paths:
        backend:
          serviceName: mvi-analyst-f-service
          servicePort: 3030
---