apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mvi-analyst
spec:
  rules:
  - host: mviapp.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mvi-analyst-f-service
            port:
              number: 3030
  ingressClassName: nginx