apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvi-analyst-b
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: mvi-analyst-b
  template:
    metadata:
      labels:
        app: mvi-analyst-b
    spec:
      containers:
        - name: app-b
          image: davidsmenesesc/rampup-back:$SHOR_SHA
          ports:
            - containerPort: 3000    
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: DB_NAME
              value: movie_db
            - name: DB_HOST
              value: "10.251.0.6"
      #   - name: cloud-sql-proxy
      #     image: gcr.io/cloudsql-docker/gce-proxy:1.28.0
      #     command:
      #         - "/cloud_sql_proxy"
      #         - "-ip_address_types=PRIVATE"
      #         - "-log_debug_stdout"
      #         - "-instances=rampup-david:us-east1:moviedb=tcp:3306"
      #         - "-credential_file=/secrets/service_account.json"
      #     securityContext:
      #       runAsNonRoot: true
      #     volumeMounts:
      #     - name: volume-db
      #       mountPath: /secrets/
      #       readOnly: true
      #     resources:
      #       requests:
      #         memory: "1Gi"
      #         cpu:    "1"
      # volumes:
      # - name: volume-db
      #   secret:
      #     secretName: secret-gcp
---
apiVersion: v1
kind: Service
metadata:
  name: mvi-analyst-b-service
spec:
  selector:
    app: mvi-analyst-b
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
