apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvi-analyst-f
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: mvi-analyst-f
  type: NodePort
  template:
    metadata:
      labels:
        app: mvi-analyst-f
    spec:
      containers:
        - name: app
          image: davidsmenesesc/rampup-front:v1
          ports:
            - containerPort: 3030
          env:
            - name: BACKEND_URL
              value: 10.102.102.94:3000
---
apiVersion: v1
kind: Service
metadata:
  name: mvi-analyst-f-service
spec:
  selector:
    app: mvi-analyst-f
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
