apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvi_analyst_b
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: mvi_analyst_b
  template:
    metadata:
      labels:
        app: mvi_analyst_b
    spec:    
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-name-db
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-host
        