apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvi-analyst-b
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: mvi-analyst-b
  template:
    metadata:
      labels:
        app: mvi-analyst-b
    spec:
      containers:
        - name: app
          image: davidsmenesesc/rampup-back:v1
          ports:
            - containerPort: 3030    
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: DB_NAME
              value: movie_db
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.0.0.preview.0
          args:
            - "--structured-logs"
            - "--port=3306"
            - "moviedb"
            - "--credentials-file=/home/sanmeneses903/key.json"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
          - name: volume-db
            mountPath: /secrets/
            readOnly: true
          resources:
            requests:
              memory: "2Gi"
              cpu:    "1"
      volumes:
        - name: volume-db
          secret:
            secretName: secret-gcp
---
apiVersion: v1
kind: Service
metadata:
  name: mvi-analyst-b-service
spec:
  selector:
    app: mvi-analyst-b
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
