apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvi_analyst_b
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: mvi_analyst_b
  template:
    metadata:
      labels:
        app: mvi_analyst_b
    spec:    
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secret/secret-movie
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: secret/secret-movie
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: secret/secret-movie
              key: database
        