apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvi-analyst-b
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: mvi-analyst-b
  template:
    metadata:
      labels:
        app: mvi-analyst-b
    spec:
        containers:
        - name: app
          image: davidsmenesesc/rampup-back:v1
          ports:
            - containerPort: 3030    
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: DB_NAME
              value: movie_db
            - name: DB_HOST
              value: 10.0.251.6
---
apiVersion: v1
kind: Service
metadata:
  name: mvi-analyst-b-service
spec:
  selector:
    app: mvi-analyst-b
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
