apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvi_analyst_b
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: mvi_analyst_b
  template:
    metadata:
      labels:
        app: mvi_analyst_b
    spec:
        containers:
        - name: app
          image: davidsmenesesc/rampup-front:v1
          ports:
            - containerPort: 3030    
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: DB_NAME
              value: movie_db
            - name: DB_HOST
              value: https://sqladmin.googleapis.com/sql/v1beta4/projects/rampup-david/instances/moviedb
        