apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
type: Opaque
data:
    mysql-root-username: dXNlcjI=
    mysql-root-password: V2lsbGViYXJkbzAx
    mysql-name-db: bW92aWVfZGI=
    mysql-host: aHR0cHM6Ly9zcWxhZG1pbi5nb29nbGVhcGlzLmNvbS9zcWwvdjFiZXRhNC9wcm9qZWN0cy9yYW1wdXAtZGF2aWQvaW5zdGFuY2VzL21vdmllZGI=