apiVersion: apps/v1
kind: Deployment
metadata:
  name: cldsql
spec:
  selector:
    matchLabels:
      app: cldsql
  template:
    metadata:
      labels:
        app: cldsql
    spec:
      containers:        
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy@sha256:5902f579e1d004b6452526433aa7b38be203c030b525c4f1ca7da6715bee8f9e 
          #gcr.io/cloud-sql-connectors/cloud-sql-proxy@sha256:4f38e32bd902caa15167b9ef79c9959cc0906884d38111a5771963489c060815
          command:
            - /cloud_sql_proxy
            - "-credentials-file=/home/sanmeneses903/key.json"
            - "instances=rampup-david:us-east1:moviedb=tcp:3306"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
          - name: volume-db
            mountPath: /secrets/
            readOnly: false
          resources:
            requests:
              memory: "1Gi"
              cpu:    "1"
      volumes:
        - name: volume-db
          secret:
            secretName: secret-gcp


