apiVersion: apps/v1
kind: Deployment
metadata:
  name: cldsql
spec:
  selector:
    matchLabels:
      app: cldsql
  template:
    metadata:
      labels:
        app: cldsql
    spec:
      containers:        
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy@sha256:4f38e32bd902caa15167b9ef79c9959cc0906884d38111a5771963489c060815
          args:
            - "--private-ip"
            - "--structured-logs"
            - "--port=3306"
            - "moviedb"
            - "--credentials-file=/secrets/key.json"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
          - name: volume-db
            mountPath: /secrets/
            readOnly: false
          resources:
            requests:
              memory: "1Gi"
              cpu:    "1"


